// Package primandproper.platform.filtering.v1 is the wire schema for the
// vocabulary of a list query: which slice of a collection a caller asked for,
// and which slice they got.
//
// This file is shipped inside the published Go module, and it is the file
// itself that is shipped -- not a copy for you to keep in sync. A consumer
// puts the module's proto directory on protoc's path and imports this file by
// its canonical name:
//
//	PLATFORM_PROTO := $(shell go list -m -f '{{.Dir}}' github.com/primandproper/platform-go/v13)/filtering/proto
//
//	protoc --proto_path proto/ --proto_path $(PLATFORM_PROTO) \
//	    --go_opt=Mprimandproper/platform/filtering/v1/filtering.proto=github.com/primandproper/platform-go/v13/filtering/filteringpb \
//	    $(CONSUMER_PROTO_FILES)   # this file deliberately absent from that list
//
// which is how google/protobuf/timestamp.proto already works in a consumer's
// own file: imported, not generated, linked against bindings that ship with
// the runtime. go.mod already pins which version of this file you get, so
// there is no protos repository to stand up and nothing to vendor.
//
// The Go bindings are pre-generated into
// github.com/primandproper/platform-go/v13/filtering/filteringpb, and the
// converters between them and the Go types live beside them in
// .../filtering/grpc. Go is the language that needs shared *code* rather than
// shared *schema*: the page-size clamp, the default, and the cursor asymmetry
// are server-side rules, and a second copy of one can be wrong in a way
// nothing reports. A generated QueryFilter in Swift, TypeScript, or Kotlin is
// a data class with eight fields and no rules to restate, so those languages
// generate from this file and need nothing else from it.
//
// go_package is here because this module generates from this file too. A
// consumer generating into its own tree overrides it with the -M mapping
// above, or with its own --go_opt, and owns its output paths entirely.
//
// Field numbers are the compatibility promise, and they are the promise across
// every language a consumer generates into. Numbers are never reused and never
// repurposed: a field that goes away is reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: primandproper/platform/filtering/v1/filtering.proto

package filteringpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryFilter is the request half: the slice of a collection a caller is
// asking for.
//
// Every field is optional and an absent one filters nothing, so the empty
// message is a request for the default page.
//
// The scalars carry explicit presence rather than leaning on a zero to mean
// "unset", so a caller that set a field to its zero value stays distinguishable
// on the wire from one that set nothing at all. What each of those means is the
// converters' business, and .../filtering/grpc documents it.
type QueryFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sort_by is a direction, not a column: "asc" for oldest first, "desc" for
	// newest first, and nothing else. It is a string rather than an enum because
	// it is one on the other transports this type crosses -- the query parameter
	// and the JSON body both carry those two words -- and an enum here would put
	// a third spelling of the same two values on the wire.
	SortBy *string `protobuf:"bytes,1,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"`
	// The four windows on when a row was created or last updated. Message fields
	// already have explicit presence, so they carry no `optional` keyword; an
	// unset one is absent exactly as an unset scalar above is.
	CreatedAfter  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_after,json=createdAfter,proto3" json:"created_after,omitempty"`
	CreatedBefore *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_before,json=createdBefore,proto3" json:"created_before,omitempty"`
	UpdatedAfter  *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_after,json=updatedAfter,proto3" json:"updated_after,omitempty"`
	UpdatedBefore *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_before,json=updatedBefore,proto3" json:"updated_before,omitempty"`
	// max_response_size is how many rows one page may hold. Absent means the
	// default; a value above the ceiling is clamped to the ceiling rather than
	// rejected.
	//
	// It is a uint32 because protobuf has no uint16, which is the type the Go
	// field it maps to actually is. That narrowing is the reason the converters
	// in .../filtering/grpc exist rather than each consumer writing their own: a
	// value that narrows before it is clamped wraps instead, and 70000 becomes a
	// legible-looking answer to a question nobody asked.
	MaxResponseSize *uint32 `protobuf:"varint,6,opt,name=max_response_size,json=maxResponseSize,proto3,oneof" json:"max_response_size,omitempty"`
	// include_archived asks for archived rows as well. Absent leaves them out.
	IncludeArchived *bool `protobuf:"varint,7,opt,name=include_archived,json=includeArchived,proto3,oneof" json:"include_archived,omitempty"`
	// cursor is an opaque value from a previous response. The page resumes after
	// the row it names; absent starts at the beginning.
	Cursor        *string `protobuf:"bytes,8,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryFilter) Reset() {
	*x = QueryFilter{}
	mi := &file_primandproper_platform_filtering_v1_filtering_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryFilter) ProtoMessage() {}

func (x *QueryFilter) ProtoReflect() protoreflect.Message {
	mi := &file_primandproper_platform_filtering_v1_filtering_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryFilter.ProtoReflect.Descriptor instead.
func (*QueryFilter) Descriptor() ([]byte, []int) {
	return file_primandproper_platform_filtering_v1_filtering_proto_rawDescGZIP(), []int{0}
}

func (x *QueryFilter) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *QueryFilter) GetCreatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAfter
	}
	return nil
}

func (x *QueryFilter) GetCreatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedBefore
	}
	return nil
}

func (x *QueryFilter) GetUpdatedAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAfter
	}
	return nil
}

func (x *QueryFilter) GetUpdatedBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedBefore
	}
	return nil
}

func (x *QueryFilter) GetMaxResponseSize() uint32 {
	if x != nil && x.MaxResponseSize != nil {
		return *x.MaxResponseSize
	}
	return 0
}

func (x *QueryFilter) GetIncludeArchived() bool {
	if x != nil && x.IncludeArchived != nil {
		return *x.IncludeArchived
	}
	return false
}

func (x *QueryFilter) GetCursor() string {
	if x != nil && x.Cursor != nil {
		return *x.Cursor
	}
	return ""
}

// Pagination is the response half: what was applied, and where the next page
// starts.
//
// Its cursors are directional and are not the same cursor. previous_cursor is
// the one that reached this page, so an empty one is the first page, and
// cursor is the one that reaches the next. Nothing has to compare them.
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// applied_query_filter is the filter this page was answered with, after
	// defaults and bounds -- not necessarily the one that was sent.
	AppliedQueryFilter *QueryFilter `protobuf:"bytes,1,opt,name=applied_query_filter,json=appliedQueryFilter,proto3" json:"applied_query_filter,omitempty"`
	// cursor reaches the page after this one. It is the last row's identifier,
	// so it is empty only when this page held no rows, and it says nothing about
	// whether a further page exists: a full page and the final page carry an
	// equally non-empty cursor.
	Cursor string `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// previous_cursor is the cursor that reached this page, echoed back from the
	// filter that was applied. Empty means the first page.
	PreviousCursor string `protobuf:"bytes,3,opt,name=previous_cursor,json=previousCursor,proto3" json:"previous_cursor,omitempty"`
	// filtered_count is how many rows matched the filter and total_count how
	// many were in scope regardless of it. Neither describes this page: they
	// describe the collection it was cut from, which is why they do not shrink
	// as a caller walks it.
	//
	// Both mean nothing unless counts_known is set.
	FilteredCount uint64 `protobuf:"varint,4,opt,name=filtered_count,json=filteredCount,proto3" json:"filtered_count,omitempty"`
	TotalCount    uint64 `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	// max_response_size is the page size that was applied, uint32 for the same
	// reason the request's is.
	MaxResponseSize uint32 `protobuf:"varint,6,opt,name=max_response_size,json=maxResponseSize,proto3" json:"max_response_size,omitempty"`
	// counts_known reports whether the counts above were answered at all.
	//
	// They are plain integers, so an unanswered pair reads as 0 and 0 -- which
	// is also what an empty collection reads as. A store whose counts ride along
	// on its rows, handed a page that came back empty, has no row to read them
	// off, so a caller walking a keyset to its end sees a final 0 that is not a
	// result. This is the field that tells those apart, and false is the default
	// so a message assembled by hand vouches for nothing until it says
	// otherwise.
	CountsKnown   bool `protobuf:"varint,7,opt,name=counts_known,json=countsKnown,proto3" json:"counts_known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_primandproper_platform_filtering_v1_filtering_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_primandproper_platform_filtering_v1_filtering_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_primandproper_platform_filtering_v1_filtering_proto_rawDescGZIP(), []int{1}
}

func (x *Pagination) GetAppliedQueryFilter() *QueryFilter {
	if x != nil {
		return x.AppliedQueryFilter
	}
	return nil
}

func (x *Pagination) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *Pagination) GetPreviousCursor() string {
	if x != nil {
		return x.PreviousCursor
	}
	return ""
}

func (x *Pagination) GetFilteredCount() uint64 {
	if x != nil {
		return x.FilteredCount
	}
	return 0
}

func (x *Pagination) GetTotalCount() uint64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *Pagination) GetMaxResponseSize() uint32 {
	if x != nil {
		return x.MaxResponseSize
	}
	return 0
}

func (x *Pagination) GetCountsKnown() bool {
	if x != nil {
		return x.CountsKnown
	}
	return false
}

var File_primandproper_platform_filtering_v1_filtering_proto protoreflect.FileDescriptor

const file_primandproper_platform_filtering_v1_filtering_proto_rawDesc = "" +
	"\n" +
	"3primandproper/platform/filtering/v1/filtering.proto\x12#primandproper.platform.filtering.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf3\x03\n" +
	"\vQueryFilter\x12\x1c\n" +
	"\asort_by\x18\x01 \x01(\tH\x00R\x06sortBy\x88\x01\x01\x12?\n" +
	"\rcreated_after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fcreatedAfter\x12A\n" +
	"\x0ecreated_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rcreatedBefore\x12?\n" +
	"\rupdated_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fupdatedAfter\x12A\n" +
	"\x0eupdated_before\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rupdatedBefore\x12/\n" +
	"\x11max_response_size\x18\x06 \x01(\rH\x01R\x0fmaxResponseSize\x88\x01\x01\x12.\n" +
	"\x10include_archived\x18\a \x01(\bH\x02R\x0fincludeArchived\x88\x01\x01\x12\x1b\n" +
	"\x06cursor\x18\b \x01(\tH\x03R\x06cursor\x88\x01\x01B\n" +
	"\n" +
	"\b_sort_byB\x14\n" +
	"\x12_max_response_sizeB\x13\n" +
	"\x11_include_archivedB\t\n" +
	"\a_cursor\"\xc8\x02\n" +
	"\n" +
	"Pagination\x12b\n" +
	"\x14applied_query_filter\x18\x01 \x01(\v20.primandproper.platform.filtering.v1.QueryFilterR\x12appliedQueryFilter\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12'\n" +
	"\x0fprevious_cursor\x18\x03 \x01(\tR\x0epreviousCursor\x12%\n" +
	"\x0efiltered_count\x18\x04 \x01(\x04R\rfilteredCount\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x04R\n" +
	"totalCount\x12*\n" +
	"\x11max_response_size\x18\x06 \x01(\rR\x0fmaxResponseSize\x12!\n" +
	"\fcounts_known\x18\a \x01(\bR\vcountsKnownBLZJgithub.com/primandproper/platform-go/v13/filtering/filteringpb;filteringpbb\x06proto3"

var (
	file_primandproper_platform_filtering_v1_filtering_proto_rawDescOnce sync.Once
	file_primandproper_platform_filtering_v1_filtering_proto_rawDescData []byte
)

func file_primandproper_platform_filtering_v1_filtering_proto_rawDescGZIP() []byte {
	file_primandproper_platform_filtering_v1_filtering_proto_rawDescOnce.Do(func() {
		file_primandproper_platform_filtering_v1_filtering_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_primandproper_platform_filtering_v1_filtering_proto_rawDesc), len(file_primandproper_platform_filtering_v1_filtering_proto_rawDesc)))
	})
	return file_primandproper_platform_filtering_v1_filtering_proto_rawDescData
}

var file_primandproper_platform_filtering_v1_filtering_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_primandproper_platform_filtering_v1_filtering_proto_goTypes = []any{
	(*QueryFilter)(nil),           // 0: primandproper.platform.filtering.v1.QueryFilter
	(*Pagination)(nil),            // 1: primandproper.platform.filtering.v1.Pagination
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_primandproper_platform_filtering_v1_filtering_proto_depIdxs = []int32{
	2, // 0: primandproper.platform.filtering.v1.QueryFilter.created_after:type_name -> google.protobuf.Timestamp
	2, // 1: primandproper.platform.filtering.v1.QueryFilter.created_before:type_name -> google.protobuf.Timestamp
	2, // 2: primandproper.platform.filtering.v1.QueryFilter.updated_after:type_name -> google.protobuf.Timestamp
	2, // 3: primandproper.platform.filtering.v1.QueryFilter.updated_before:type_name -> google.protobuf.Timestamp
	0, // 4: primandproper.platform.filtering.v1.Pagination.applied_query_filter:type_name -> primandproper.platform.filtering.v1.QueryFilter
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_primandproper_platform_filtering_v1_filtering_proto_init() }
func file_primandproper_platform_filtering_v1_filtering_proto_init() {
	if File_primandproper_platform_filtering_v1_filtering_proto != nil {
		return
	}
	file_primandproper_platform_filtering_v1_filtering_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_primandproper_platform_filtering_v1_filtering_proto_rawDesc), len(file_primandproper_platform_filtering_v1_filtering_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_primandproper_platform_filtering_v1_filtering_proto_goTypes,
		DependencyIndexes: file_primandproper_platform_filtering_v1_filtering_proto_depIdxs,
		MessageInfos:      file_primandproper_platform_filtering_v1_filtering_proto_msgTypes,
	}.Build()
	File_primandproper_platform_filtering_v1_filtering_proto = out.File
	file_primandproper_platform_filtering_v1_filtering_proto_goTypes = nil
	file_primandproper_platform_filtering_v1_filtering_proto_depIdxs = nil
}
