// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package webauthnmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v10/authentication/webauthn"
)

// Ensure, that SessionStoreMock does implement webauthn.SessionStore.
// If this is not the case, regenerate this file with moq.
var _ webauthn.SessionStore = &SessionStoreMock{}

// SessionStoreMock is a mock implementation of webauthn.SessionStore.
//
//	func TestSomethingThatUsesSessionStore(t *testing.T) {
//
//		// make and configure a mocked webauthn.SessionStore
//		mockedSessionStore := &SessionStoreMock{
//			ConsumeFunc: func(ctx context.Context, challenge string) (*webauthn.SessionData, error) {
//				panic("mock out the Consume method")
//			},
//			SaveFunc: func(ctx context.Context, session *webauthn.SessionData, ttl time.Duration) error {
//				panic("mock out the Save method")
//			},
//		}
//
//		// use mockedSessionStore in code that requires webauthn.SessionStore
//		// and then make assertions.
//
//	}
type SessionStoreMock struct {
	// ConsumeFunc mocks the Consume method.
	ConsumeFunc func(ctx context.Context, challenge string) (*webauthn.SessionData, error)

	// SaveFunc mocks the Save method.
	SaveFunc func(ctx context.Context, session *webauthn.SessionData, ttl time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// Consume holds details about calls to the Consume method.
		Consume []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Challenge is the challenge argument value.
			Challenge string
		}
		// Save holds details about calls to the Save method.
		Save []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Session is the session argument value.
			Session *webauthn.SessionData
			// TTL is the ttl argument value.
			TTL time.Duration
		}
	}
	lockConsume sync.RWMutex
	lockSave    sync.RWMutex
}

// Consume calls ConsumeFunc.
func (mock *SessionStoreMock) Consume(ctx context.Context, challenge string) (*webauthn.SessionData, error) {
	if mock.ConsumeFunc == nil {
		panic("SessionStoreMock.ConsumeFunc: method is nil but SessionStore.Consume was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Challenge string
	}{
		Ctx:       ctx,
		Challenge: challenge,
	}
	mock.lockConsume.Lock()
	mock.calls.Consume = append(mock.calls.Consume, callInfo)
	mock.lockConsume.Unlock()
	return mock.ConsumeFunc(ctx, challenge)
}

// ConsumeCalls gets all the calls that were made to Consume.
// Check the length with:
//
//	len(mockedSessionStore.ConsumeCalls())
func (mock *SessionStoreMock) ConsumeCalls() []struct {
	Ctx       context.Context
	Challenge string
} {
	var calls []struct {
		Ctx       context.Context
		Challenge string
	}
	mock.lockConsume.RLock()
	calls = mock.calls.Consume
	mock.lockConsume.RUnlock()
	return calls
}

// Save calls SaveFunc.
func (mock *SessionStoreMock) Save(ctx context.Context, session *webauthn.SessionData, ttl time.Duration) error {
	if mock.SaveFunc == nil {
		panic("SessionStoreMock.SaveFunc: method is nil but SessionStore.Save was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Session *webauthn.SessionData
		TTL     time.Duration
	}{
		Ctx:     ctx,
		Session: session,
		TTL:     ttl,
	}
	mock.lockSave.Lock()
	mock.calls.Save = append(mock.calls.Save, callInfo)
	mock.lockSave.Unlock()
	return mock.SaveFunc(ctx, session, ttl)
}

// SaveCalls gets all the calls that were made to Save.
// Check the length with:
//
//	len(mockedSessionStore.SaveCalls())
func (mock *SessionStoreMock) SaveCalls() []struct {
	Ctx     context.Context
	Session *webauthn.SessionData
	TTL     time.Duration
} {
	var calls []struct {
		Ctx     context.Context
		Session *webauthn.SessionData
		TTL     time.Duration
	}
	mock.lockSave.RLock()
	calls = mock.calls.Save
	mock.lockSave.RUnlock()
	return calls
}
