// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v6/cache"
)

// Ensure, that BatchCacheMock does implement cache.BatchCache.
// If this is not the case, regenerate this file with moq.
var _ cache.BatchCache[any] = &BatchCacheMock[any]{}

// BatchCacheMock is a mock implementation of cache.BatchCache.
//
//	func TestSomethingThatUsesBatchCache(t *testing.T) {
//
//		// make and configure a mocked cache.BatchCache
//		mockedBatchCache := &BatchCacheMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, key string) (*T, error) {
//				panic("mock out the Get method")
//			},
//			GetManyFunc: func(ctx context.Context, keys []string) (map[string]*T, error) {
//				panic("mock out the GetMany method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//			SetFunc: func(ctx context.Context, key string, value *T) error {
//				panic("mock out the Set method")
//			},
//			SetManyFunc: func(ctx context.Context, items map[string]*T) error {
//				panic("mock out the SetMany method")
//			},
//		}
//
//		// use mockedBatchCache in code that requires cache.BatchCache
//		// and then make assertions.
//
//	}
type BatchCacheMock[T any] struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) (*T, error)

	// GetManyFunc mocks the GetMany method.
	GetManyFunc func(ctx context.Context, keys []string) (map[string]*T, error)

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value *T) error

	// SetManyFunc mocks the SetMany method.
	SetManyFunc func(ctx context.Context, items map[string]*T) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetMany holds details about calls to the GetMany method.
		GetMany []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []string
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value *T
		}
		// SetMany holds details about calls to the SetMany method.
		SetMany []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Items is the items argument value.
			Items map[string]*T
		}
	}
	lockDelete  sync.RWMutex
	lockGet     sync.RWMutex
	lockGetMany sync.RWMutex
	lockPing    sync.RWMutex
	lockSet     sync.RWMutex
	lockSetMany sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *BatchCacheMock[T]) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("BatchCacheMock.DeleteFunc: method is nil but BatchCache.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedBatchCache.DeleteCalls())
func (mock *BatchCacheMock[T]) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *BatchCacheMock[T]) Get(ctx context.Context, key string) (*T, error) {
	if mock.GetFunc == nil {
		panic("BatchCacheMock.GetFunc: method is nil but BatchCache.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedBatchCache.GetCalls())
func (mock *BatchCacheMock[T]) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetMany calls GetManyFunc.
func (mock *BatchCacheMock[T]) GetMany(ctx context.Context, keys []string) (map[string]*T, error) {
	if mock.GetManyFunc == nil {
		panic("BatchCacheMock.GetManyFunc: method is nil but BatchCache.GetMany was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []string
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockGetMany.Lock()
	mock.calls.GetMany = append(mock.calls.GetMany, callInfo)
	mock.lockGetMany.Unlock()
	return mock.GetManyFunc(ctx, keys)
}

// GetManyCalls gets all the calls that were made to GetMany.
// Check the length with:
//
//	len(mockedBatchCache.GetManyCalls())
func (mock *BatchCacheMock[T]) GetManyCalls() []struct {
	Ctx  context.Context
	Keys []string
} {
	var calls []struct {
		Ctx  context.Context
		Keys []string
	}
	mock.lockGetMany.RLock()
	calls = mock.calls.GetMany
	mock.lockGetMany.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *BatchCacheMock[T]) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("BatchCacheMock.PingFunc: method is nil but BatchCache.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedBatchCache.PingCalls())
func (mock *BatchCacheMock[T]) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *BatchCacheMock[T]) Set(ctx context.Context, key string, value *T) error {
	if mock.SetFunc == nil {
		panic("BatchCacheMock.SetFunc: method is nil but BatchCache.Set was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Key   string
		Value *T
	}{
		Ctx:   ctx,
		Key:   key,
		Value: value,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedBatchCache.SetCalls())
func (mock *BatchCacheMock[T]) SetCalls() []struct {
	Ctx   context.Context
	Key   string
	Value *T
} {
	var calls []struct {
		Ctx   context.Context
		Key   string
		Value *T
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// SetMany calls SetManyFunc.
func (mock *BatchCacheMock[T]) SetMany(ctx context.Context, items map[string]*T) error {
	if mock.SetManyFunc == nil {
		panic("BatchCacheMock.SetManyFunc: method is nil but BatchCache.SetMany was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Items map[string]*T
	}{
		Ctx:   ctx,
		Items: items,
	}
	mock.lockSetMany.Lock()
	mock.calls.SetMany = append(mock.calls.SetMany, callInfo)
	mock.lockSetMany.Unlock()
	return mock.SetManyFunc(ctx, items)
}

// SetManyCalls gets all the calls that were made to SetMany.
// Check the length with:
//
//	len(mockedBatchCache.SetManyCalls())
func (mock *BatchCacheMock[T]) SetManyCalls() []struct {
	Ctx   context.Context
	Items map[string]*T
} {
	var calls []struct {
		Ctx   context.Context
		Items map[string]*T
	}
	mock.lockSetMany.RLock()
	calls = mock.calls.SetMany
	mock.lockSetMany.RUnlock()
	return calls
}
