// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mockrouting

import (
	"net/http"
	"sync"

	"github.com/primandproper/platform-go/v6/routing"
)

// Ensure, that BackendMock does implement routing.Backend.
// If this is not the case, regenerate this file with moq.
var _ routing.Backend = &BackendMock{}

// BackendMock is a mock implementation of routing.Backend.
//
//	func TestSomethingThatUsesBackend(t *testing.T) {
//
//		// make and configure a mocked routing.Backend
//		mockedBackend := &BackendMock{
//			HandleFunc: func(method string, pattern string, handler http.Handler)  {
//				panic("mock out the Handle method")
//			},
//			HandlerFunc: func() http.Handler {
//				panic("mock out the Handler method")
//			},
//			PathValueFunc: func(req *http.Request, name string) string {
//				panic("mock out the PathValue method")
//			},
//			UseFunc: func(middleware ...routing.Middleware)  {
//				panic("mock out the Use method")
//			},
//		}
//
//		// use mockedBackend in code that requires routing.Backend
//		// and then make assertions.
//
//	}
type BackendMock struct {
	// HandleFunc mocks the Handle method.
	HandleFunc func(method string, pattern string, handler http.Handler)

	// HandlerFunc mocks the Handler method.
	HandlerFunc func() http.Handler

	// PathValueFunc mocks the PathValue method.
	PathValueFunc func(req *http.Request, name string) string

	// UseFunc mocks the Use method.
	UseFunc func(middleware ...routing.Middleware)

	// calls tracks calls to the methods.
	calls struct {
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Method is the method argument value.
			Method string
			// Pattern is the pattern argument value.
			Pattern string
			// Handler is the handler argument value.
			Handler http.Handler
		}
		// Handler holds details about calls to the Handler method.
		Handler []struct {
		}
		// PathValue holds details about calls to the PathValue method.
		PathValue []struct {
			// Req is the req argument value.
			Req *http.Request
			// Name is the name argument value.
			Name string
		}
		// Use holds details about calls to the Use method.
		Use []struct {
			// Middleware is the middleware argument value.
			Middleware []routing.Middleware
		}
	}
	lockHandle    sync.RWMutex
	lockHandler   sync.RWMutex
	lockPathValue sync.RWMutex
	lockUse       sync.RWMutex
}

// Handle calls HandleFunc.
func (mock *BackendMock) Handle(method string, pattern string, handler http.Handler) {
	if mock.HandleFunc == nil {
		panic("BackendMock.HandleFunc: method is nil but Backend.Handle was just called")
	}
	callInfo := struct {
		Method  string
		Pattern string
		Handler http.Handler
	}{
		Method:  method,
		Pattern: pattern,
		Handler: handler,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	mock.HandleFunc(method, pattern, handler)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedBackend.HandleCalls())
func (mock *BackendMock) HandleCalls() []struct {
	Method  string
	Pattern string
	Handler http.Handler
} {
	var calls []struct {
		Method  string
		Pattern string
		Handler http.Handler
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}

// Handler calls HandlerFunc.
func (mock *BackendMock) Handler() http.Handler {
	if mock.HandlerFunc == nil {
		panic("BackendMock.HandlerFunc: method is nil but Backend.Handler was just called")
	}
	callInfo := struct {
	}{}
	mock.lockHandler.Lock()
	mock.calls.Handler = append(mock.calls.Handler, callInfo)
	mock.lockHandler.Unlock()
	return mock.HandlerFunc()
}

// HandlerCalls gets all the calls that were made to Handler.
// Check the length with:
//
//	len(mockedBackend.HandlerCalls())
func (mock *BackendMock) HandlerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockHandler.RLock()
	calls = mock.calls.Handler
	mock.lockHandler.RUnlock()
	return calls
}

// PathValue calls PathValueFunc.
func (mock *BackendMock) PathValue(req *http.Request, name string) string {
	if mock.PathValueFunc == nil {
		panic("BackendMock.PathValueFunc: method is nil but Backend.PathValue was just called")
	}
	callInfo := struct {
		Req  *http.Request
		Name string
	}{
		Req:  req,
		Name: name,
	}
	mock.lockPathValue.Lock()
	mock.calls.PathValue = append(mock.calls.PathValue, callInfo)
	mock.lockPathValue.Unlock()
	return mock.PathValueFunc(req, name)
}

// PathValueCalls gets all the calls that were made to PathValue.
// Check the length with:
//
//	len(mockedBackend.PathValueCalls())
func (mock *BackendMock) PathValueCalls() []struct {
	Req  *http.Request
	Name string
} {
	var calls []struct {
		Req  *http.Request
		Name string
	}
	mock.lockPathValue.RLock()
	calls = mock.calls.PathValue
	mock.lockPathValue.RUnlock()
	return calls
}

// Use calls UseFunc.
func (mock *BackendMock) Use(middleware ...routing.Middleware) {
	if mock.UseFunc == nil {
		panic("BackendMock.UseFunc: method is nil but Backend.Use was just called")
	}
	callInfo := struct {
		Middleware []routing.Middleware
	}{
		Middleware: middleware,
	}
	mock.lockUse.Lock()
	mock.calls.Use = append(mock.calls.Use, callInfo)
	mock.lockUse.Unlock()
	mock.UseFunc(middleware...)
}

// UseCalls gets all the calls that were made to Use.
// Check the length with:
//
//	len(mockedBackend.UseCalls())
func (mock *BackendMock) UseCalls() []struct {
	Middleware []routing.Middleware
} {
	var calls []struct {
		Middleware []routing.Middleware
	}
	mock.lockUse.RLock()
	calls = mock.calls.Use
	mock.lockUse.RUnlock()
	return calls
}
