// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/primandproper/platform-go/v8/eventcapture"
)

// Ensure, that SinkMock does implement eventcapture.Sink.
// If this is not the case, regenerate this file with moq.
var _ eventcapture.Sink = &SinkMock{}

// SinkMock is a mock implementation of eventcapture.Sink.
//
//	func TestSomethingThatUsesSink(t *testing.T) {
//
//		// make and configure a mocked eventcapture.Sink
//		mockedSink := &SinkMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			FlushFunc: func() error {
//				panic("mock out the Flush method")
//			},
//			WriteFunc: func(record any) error {
//				panic("mock out the Write method")
//			},
//		}
//
//		// use mockedSink in code that requires eventcapture.Sink
//		// and then make assertions.
//
//	}
type SinkMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// FlushFunc mocks the Flush method.
	FlushFunc func() error

	// WriteFunc mocks the Write method.
	WriteFunc func(record any) error

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Flush holds details about calls to the Flush method.
		Flush []struct {
		}
		// Write holds details about calls to the Write method.
		Write []struct {
			// Record is the record argument value.
			Record any
		}
	}
	lockClose sync.RWMutex
	lockFlush sync.RWMutex
	lockWrite sync.RWMutex
}

// Close calls CloseFunc.
func (mock *SinkMock) Close() error {
	if mock.CloseFunc == nil {
		panic("SinkMock.CloseFunc: method is nil but Sink.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedSink.CloseCalls())
func (mock *SinkMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Flush calls FlushFunc.
func (mock *SinkMock) Flush() error {
	if mock.FlushFunc == nil {
		panic("SinkMock.FlushFunc: method is nil but Sink.Flush was just called")
	}
	callInfo := struct {
	}{}
	mock.lockFlush.Lock()
	mock.calls.Flush = append(mock.calls.Flush, callInfo)
	mock.lockFlush.Unlock()
	return mock.FlushFunc()
}

// FlushCalls gets all the calls that were made to Flush.
// Check the length with:
//
//	len(mockedSink.FlushCalls())
func (mock *SinkMock) FlushCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockFlush.RLock()
	calls = mock.calls.Flush
	mock.lockFlush.RUnlock()
	return calls
}

// Write calls WriteFunc.
func (mock *SinkMock) Write(record any) error {
	if mock.WriteFunc == nil {
		panic("SinkMock.WriteFunc: method is nil but Sink.Write was just called")
	}
	callInfo := struct {
		Record any
	}{
		Record: record,
	}
	mock.lockWrite.Lock()
	mock.calls.Write = append(mock.calls.Write, callInfo)
	mock.lockWrite.Unlock()
	return mock.WriteFunc(record)
}

// WriteCalls gets all the calls that were made to Write.
// Check the length with:
//
//	len(mockedSink.WriteCalls())
func (mock *SinkMock) WriteCalls() []struct {
	Record any
} {
	var calls []struct {
		Record any
	}
	mock.lockWrite.RLock()
	calls = mock.calls.Write
	mock.lockWrite.RUnlock()
	return calls
}
