// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package redis

import (
	"context"
	"sync"
	"time"

	"github.com/redis/go-redis/v9"
)

// Ensure, that redisClientMock does implement redisClient.
// If this is not the case, regenerate this file with moq.
var _ redisClient = &redisClientMock{}

// redisClientMock is a mock implementation of redisClient.
//
//	func TestSomethingThatUsesredisClient(t *testing.T) {
//
//		// make and configure a mocked redisClient
//		mockedredisClient := &redisClientMock{
//			DelFunc: func(ctx context.Context, keys ...string) *redis.IntCmd {
//				panic("mock out the Del method")
//			},
//			EvalFunc: func(ctx context.Context, script string, keys []string, args ...any) *redis.Cmd {
//				panic("mock out the Eval method")
//			},
//			GetFunc: func(ctx context.Context, key string) *redis.StringCmd {
//				panic("mock out the Get method")
//			},
//			MGetFunc: func(ctx context.Context, keys ...string) *redis.SliceCmd {
//				panic("mock out the MGet method")
//			},
//			PingFunc: func(ctx context.Context) *redis.StatusCmd {
//				panic("mock out the Ping method")
//			},
//			SetFunc: func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedredisClient in code that requires redisClient
//		// and then make assertions.
//
//	}
type redisClientMock struct {
	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, keys ...string) *redis.IntCmd

	// EvalFunc mocks the Eval method.
	EvalFunc func(ctx context.Context, script string, keys []string, args ...any) *redis.Cmd

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) *redis.StringCmd

	// MGetFunc mocks the MGet method.
	MGetFunc func(ctx context.Context, keys ...string) *redis.SliceCmd

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) *redis.StatusCmd

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []string
		}
		// Eval holds details about calls to the Eval method.
		Eval []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Script is the script argument value.
			Script string
			// Keys is the keys argument value.
			Keys []string
			// Args is the args argument value.
			Args []any
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// MGet holds details about calls to the MGet method.
		MGet []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Keys is the keys argument value.
			Keys []string
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value any
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
	}
	lockDel  sync.RWMutex
	lockEval sync.RWMutex
	lockGet  sync.RWMutex
	lockMGet sync.RWMutex
	lockPing sync.RWMutex
	lockSet  sync.RWMutex
}

// Del calls DelFunc.
func (mock *redisClientMock) Del(ctx context.Context, keys ...string) *redis.IntCmd {
	if mock.DelFunc == nil {
		panic("redisClientMock.DelFunc: method is nil but redisClient.Del was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []string
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	return mock.DelFunc(ctx, keys...)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedredisClient.DelCalls())
func (mock *redisClientMock) DelCalls() []struct {
	Ctx  context.Context
	Keys []string
} {
	var calls []struct {
		Ctx  context.Context
		Keys []string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// Eval calls EvalFunc.
func (mock *redisClientMock) Eval(ctx context.Context, script string, keys []string, args ...any) *redis.Cmd {
	if mock.EvalFunc == nil {
		panic("redisClientMock.EvalFunc: method is nil but redisClient.Eval was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Script string
		Keys   []string
		Args   []any
	}{
		Ctx:    ctx,
		Script: script,
		Keys:   keys,
		Args:   args,
	}
	mock.lockEval.Lock()
	mock.calls.Eval = append(mock.calls.Eval, callInfo)
	mock.lockEval.Unlock()
	return mock.EvalFunc(ctx, script, keys, args...)
}

// EvalCalls gets all the calls that were made to Eval.
// Check the length with:
//
//	len(mockedredisClient.EvalCalls())
func (mock *redisClientMock) EvalCalls() []struct {
	Ctx    context.Context
	Script string
	Keys   []string
	Args   []any
} {
	var calls []struct {
		Ctx    context.Context
		Script string
		Keys   []string
		Args   []any
	}
	mock.lockEval.RLock()
	calls = mock.calls.Eval
	mock.lockEval.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *redisClientMock) Get(ctx context.Context, key string) *redis.StringCmd {
	if mock.GetFunc == nil {
		panic("redisClientMock.GetFunc: method is nil but redisClient.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedredisClient.GetCalls())
func (mock *redisClientMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// MGet calls MGetFunc.
func (mock *redisClientMock) MGet(ctx context.Context, keys ...string) *redis.SliceCmd {
	if mock.MGetFunc == nil {
		panic("redisClientMock.MGetFunc: method is nil but redisClient.MGet was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Keys []string
	}{
		Ctx:  ctx,
		Keys: keys,
	}
	mock.lockMGet.Lock()
	mock.calls.MGet = append(mock.calls.MGet, callInfo)
	mock.lockMGet.Unlock()
	return mock.MGetFunc(ctx, keys...)
}

// MGetCalls gets all the calls that were made to MGet.
// Check the length with:
//
//	len(mockedredisClient.MGetCalls())
func (mock *redisClientMock) MGetCalls() []struct {
	Ctx  context.Context
	Keys []string
} {
	var calls []struct {
		Ctx  context.Context
		Keys []string
	}
	mock.lockMGet.RLock()
	calls = mock.calls.MGet
	mock.lockMGet.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *redisClientMock) Ping(ctx context.Context) *redis.StatusCmd {
	if mock.PingFunc == nil {
		panic("redisClientMock.PingFunc: method is nil but redisClient.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedredisClient.PingCalls())
func (mock *redisClientMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *redisClientMock) Set(ctx context.Context, key string, value any, expiration time.Duration) *redis.StatusCmd {
	if mock.SetFunc == nil {
		panic("redisClientMock.SetFunc: method is nil but redisClient.Set was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, expiration)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedredisClient.SetCalls())
func (mock *redisClientMock) SetCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      any
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      any
		Expiration time.Duration
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
