// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package encryptionmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v12/cryptography/encryption"
)

// Ensure, that CipherMock does implement encryption.Cipher.
// If this is not the case, regenerate this file with moq.
var _ encryption.Cipher = &CipherMock{}

// CipherMock is a mock implementation of encryption.Cipher.
//
//	func TestSomethingThatUsesCipher(t *testing.T) {
//
//		// make and configure a mocked encryption.Cipher
//		mockedCipher := &CipherMock{
//			OpenFunc: func(ctx context.Context, ciphertext []byte, associatedData []byte) ([]byte, error) {
//				panic("mock out the Open method")
//			},
//			SealFunc: func(ctx context.Context, plaintext []byte, associatedData []byte) ([]byte, error) {
//				panic("mock out the Seal method")
//			},
//		}
//
//		// use mockedCipher in code that requires encryption.Cipher
//		// and then make assertions.
//
//	}
type CipherMock struct {
	// OpenFunc mocks the Open method.
	OpenFunc func(ctx context.Context, ciphertext []byte, associatedData []byte) ([]byte, error)

	// SealFunc mocks the Seal method.
	SealFunc func(ctx context.Context, plaintext []byte, associatedData []byte) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Open holds details about calls to the Open method.
		Open []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Ciphertext is the ciphertext argument value.
			Ciphertext []byte
			// AssociatedData is the associatedData argument value.
			AssociatedData []byte
		}
		// Seal holds details about calls to the Seal method.
		Seal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Plaintext is the plaintext argument value.
			Plaintext []byte
			// AssociatedData is the associatedData argument value.
			AssociatedData []byte
		}
	}
	lockOpen sync.RWMutex
	lockSeal sync.RWMutex
}

// Open calls OpenFunc.
func (mock *CipherMock) Open(ctx context.Context, ciphertext []byte, associatedData []byte) ([]byte, error) {
	if mock.OpenFunc == nil {
		panic("CipherMock.OpenFunc: method is nil but Cipher.Open was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Ciphertext     []byte
		AssociatedData []byte
	}{
		Ctx:            ctx,
		Ciphertext:     ciphertext,
		AssociatedData: associatedData,
	}
	mock.lockOpen.Lock()
	mock.calls.Open = append(mock.calls.Open, callInfo)
	mock.lockOpen.Unlock()
	return mock.OpenFunc(ctx, ciphertext, associatedData)
}

// OpenCalls gets all the calls that were made to Open.
// Check the length with:
//
//	len(mockedCipher.OpenCalls())
func (mock *CipherMock) OpenCalls() []struct {
	Ctx            context.Context
	Ciphertext     []byte
	AssociatedData []byte
} {
	var calls []struct {
		Ctx            context.Context
		Ciphertext     []byte
		AssociatedData []byte
	}
	mock.lockOpen.RLock()
	calls = mock.calls.Open
	mock.lockOpen.RUnlock()
	return calls
}

// Seal calls SealFunc.
func (mock *CipherMock) Seal(ctx context.Context, plaintext []byte, associatedData []byte) ([]byte, error) {
	if mock.SealFunc == nil {
		panic("CipherMock.SealFunc: method is nil but Cipher.Seal was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Plaintext      []byte
		AssociatedData []byte
	}{
		Ctx:            ctx,
		Plaintext:      plaintext,
		AssociatedData: associatedData,
	}
	mock.lockSeal.Lock()
	mock.calls.Seal = append(mock.calls.Seal, callInfo)
	mock.lockSeal.Unlock()
	return mock.SealFunc(ctx, plaintext, associatedData)
}

// SealCalls gets all the calls that were made to Seal.
// Check the length with:
//
//	len(mockedCipher.SealCalls())
func (mock *CipherMock) SealCalls() []struct {
	Ctx            context.Context
	Plaintext      []byte
	AssociatedData []byte
} {
	var calls []struct {
		Ctx            context.Context
		Plaintext      []byte
		AssociatedData []byte
	}
	mock.lockSeal.RLock()
	calls = mock.calls.Seal
	mock.lockSeal.RUnlock()
	return calls
}
