// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package encryptionmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v14/cryptography/encryption"
)

// Ensure, that KeyWrapperMock does implement encryption.KeyWrapper.
// If this is not the case, regenerate this file with moq.
var _ encryption.KeyWrapper = &KeyWrapperMock{}

// KeyWrapperMock is a mock implementation of encryption.KeyWrapper.
//
//	func TestSomethingThatUsesKeyWrapper(t *testing.T) {
//
//		// make and configure a mocked encryption.KeyWrapper
//		mockedKeyWrapper := &KeyWrapperMock{
//			UnwrapFunc: func(ctx context.Context, wrapped []byte, associatedData []byte) ([]byte, error) {
//				panic("mock out the Unwrap method")
//			},
//			WrapFunc: func(ctx context.Context, key []byte, associatedData []byte) ([]byte, error) {
//				panic("mock out the Wrap method")
//			},
//		}
//
//		// use mockedKeyWrapper in code that requires encryption.KeyWrapper
//		// and then make assertions.
//
//	}
type KeyWrapperMock struct {
	// UnwrapFunc mocks the Unwrap method.
	UnwrapFunc func(ctx context.Context, wrapped []byte, associatedData []byte) ([]byte, error)

	// WrapFunc mocks the Wrap method.
	WrapFunc func(ctx context.Context, key []byte, associatedData []byte) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Unwrap holds details about calls to the Unwrap method.
		Unwrap []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Wrapped is the wrapped argument value.
			Wrapped []byte
			// AssociatedData is the associatedData argument value.
			AssociatedData []byte
		}
		// Wrap holds details about calls to the Wrap method.
		Wrap []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key []byte
			// AssociatedData is the associatedData argument value.
			AssociatedData []byte
		}
	}
	lockUnwrap sync.RWMutex
	lockWrap   sync.RWMutex
}

// Unwrap calls UnwrapFunc.
func (mock *KeyWrapperMock) Unwrap(ctx context.Context, wrapped []byte, associatedData []byte) ([]byte, error) {
	if mock.UnwrapFunc == nil {
		panic("KeyWrapperMock.UnwrapFunc: method is nil but KeyWrapper.Unwrap was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Wrapped        []byte
		AssociatedData []byte
	}{
		Ctx:            ctx,
		Wrapped:        wrapped,
		AssociatedData: associatedData,
	}
	mock.lockUnwrap.Lock()
	mock.calls.Unwrap = append(mock.calls.Unwrap, callInfo)
	mock.lockUnwrap.Unlock()
	return mock.UnwrapFunc(ctx, wrapped, associatedData)
}

// UnwrapCalls gets all the calls that were made to Unwrap.
// Check the length with:
//
//	len(mockedKeyWrapper.UnwrapCalls())
func (mock *KeyWrapperMock) UnwrapCalls() []struct {
	Ctx            context.Context
	Wrapped        []byte
	AssociatedData []byte
} {
	var calls []struct {
		Ctx            context.Context
		Wrapped        []byte
		AssociatedData []byte
	}
	mock.lockUnwrap.RLock()
	calls = mock.calls.Unwrap
	mock.lockUnwrap.RUnlock()
	return calls
}

// Wrap calls WrapFunc.
func (mock *KeyWrapperMock) Wrap(ctx context.Context, key []byte, associatedData []byte) ([]byte, error) {
	if mock.WrapFunc == nil {
		panic("KeyWrapperMock.WrapFunc: method is nil but KeyWrapper.Wrap was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		Key            []byte
		AssociatedData []byte
	}{
		Ctx:            ctx,
		Key:            key,
		AssociatedData: associatedData,
	}
	mock.lockWrap.Lock()
	mock.calls.Wrap = append(mock.calls.Wrap, callInfo)
	mock.lockWrap.Unlock()
	return mock.WrapFunc(ctx, key, associatedData)
}

// WrapCalls gets all the calls that were made to Wrap.
// Check the length with:
//
//	len(mockedKeyWrapper.WrapCalls())
func (mock *KeyWrapperMock) WrapCalls() []struct {
	Ctx            context.Context
	Key            []byte
	AssociatedData []byte
} {
	var calls []struct {
		Ctx            context.Context
		Key            []byte
		AssociatedData []byte
	}
	mock.lockWrap.RLock()
	calls = mock.calls.Wrap
	mock.lockWrap.RUnlock()
	return calls
}
