// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package capitalismmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v9/capitalism"
)

// Ensure, that UsageReporterMock does implement capitalism.UsageReporter.
// If this is not the case, regenerate this file with moq.
var _ capitalism.UsageReporter = &UsageReporterMock{}

// UsageReporterMock is a mock implementation of capitalism.UsageReporter.
//
//	func TestSomethingThatUsesUsageReporter(t *testing.T) {
//
//		// make and configure a mocked capitalism.UsageReporter
//		mockedUsageReporter := &UsageReporterMock{
//			ReportUsageFunc: func(ctx context.Context, input *capitalism.UsageReportInput) error {
//				panic("mock out the ReportUsage method")
//			},
//		}
//
//		// use mockedUsageReporter in code that requires capitalism.UsageReporter
//		// and then make assertions.
//
//	}
type UsageReporterMock struct {
	// ReportUsageFunc mocks the ReportUsage method.
	ReportUsageFunc func(ctx context.Context, input *capitalism.UsageReportInput) error

	// calls tracks calls to the methods.
	calls struct {
		// ReportUsage holds details about calls to the ReportUsage method.
		ReportUsage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Input is the input argument value.
			Input *capitalism.UsageReportInput
		}
	}
	lockReportUsage sync.RWMutex
}

// ReportUsage calls ReportUsageFunc.
func (mock *UsageReporterMock) ReportUsage(ctx context.Context, input *capitalism.UsageReportInput) error {
	if mock.ReportUsageFunc == nil {
		panic("UsageReporterMock.ReportUsageFunc: method is nil but UsageReporter.ReportUsage was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Input *capitalism.UsageReportInput
	}{
		Ctx:   ctx,
		Input: input,
	}
	mock.lockReportUsage.Lock()
	mock.calls.ReportUsage = append(mock.calls.ReportUsage, callInfo)
	mock.lockReportUsage.Unlock()
	return mock.ReportUsageFunc(ctx, input)
}

// ReportUsageCalls gets all the calls that were made to ReportUsage.
// Check the length with:
//
//	len(mockedUsageReporter.ReportUsageCalls())
func (mock *UsageReporterMock) ReportUsageCalls() []struct {
	Ctx   context.Context
	Input *capitalism.UsageReportInput
} {
	var calls []struct {
		Ctx   context.Context
		Input *capitalism.UsageReportInput
	}
	mock.lockReportUsage.RLock()
	calls = mock.calls.ReportUsage
	mock.lockReportUsage.RUnlock()
	return calls
}
