// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"sync"

	"github.com/primandproper/platform-go/v4/circuitbreaking"
	"github.com/primandproper/platform-go/v4/circuitbreaking/partitioned"
)

// Ensure, that KeyedCircuitBreakerMock does implement partitioned.KeyedCircuitBreaker.
// If this is not the case, regenerate this file with moq.
var _ partitioned.KeyedCircuitBreaker = &KeyedCircuitBreakerMock{}

// KeyedCircuitBreakerMock is a mock implementation of partitioned.KeyedCircuitBreaker.
//
//	func TestSomethingThatUsesKeyedCircuitBreaker(t *testing.T) {
//
//		// make and configure a mocked partitioned.KeyedCircuitBreaker
//		mockedKeyedCircuitBreaker := &KeyedCircuitBreakerMock{
//			ForFunc: func(key string) circuitbreaking.CircuitBreaker {
//				panic("mock out the For method")
//			},
//		}
//
//		// use mockedKeyedCircuitBreaker in code that requires partitioned.KeyedCircuitBreaker
//		// and then make assertions.
//
//	}
type KeyedCircuitBreakerMock struct {
	// ForFunc mocks the For method.
	ForFunc func(key string) circuitbreaking.CircuitBreaker

	// calls tracks calls to the methods.
	calls struct {
		// For holds details about calls to the For method.
		For []struct {
			// Key is the key argument value.
			Key string
		}
	}
	lockFor sync.RWMutex
}

// For calls ForFunc.
func (mock *KeyedCircuitBreakerMock) For(key string) circuitbreaking.CircuitBreaker {
	if mock.ForFunc == nil {
		panic("KeyedCircuitBreakerMock.ForFunc: method is nil but KeyedCircuitBreaker.For was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockFor.Lock()
	mock.calls.For = append(mock.calls.For, callInfo)
	mock.lockFor.Unlock()
	return mock.ForFunc(key)
}

// ForCalls gets all the calls that were made to For.
// Check the length with:
//
//	len(mockedKeyedCircuitBreaker.ForCalls())
func (mock *KeyedCircuitBreakerMock) ForCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockFor.RLock()
	calls = mock.calls.For
	mock.lockFor.RUnlock()
	return calls
}
