// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package llmmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v10/llm"
)

// Ensure, that ProviderMock does implement llm.Provider.
// If this is not the case, regenerate this file with moq.
var _ llm.Provider = &ProviderMock{}

// ProviderMock is a mock implementation of llm.Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked llm.Provider
//		mockedProvider := &ProviderMock{
//			CapabilitiesFunc: func() llm.Capabilities {
//				panic("mock out the Capabilities method")
//			},
//			CompletionFunc: func(ctx context.Context, req *llm.CompletionRequest) (*llm.CompletionResponse, error) {
//				panic("mock out the Completion method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			StreamFunc: func(ctx context.Context, req *llm.CompletionRequest) (llm.Stream, error) {
//				panic("mock out the Stream method")
//			},
//		}
//
//		// use mockedProvider in code that requires llm.Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// CapabilitiesFunc mocks the Capabilities method.
	CapabilitiesFunc func() llm.Capabilities

	// CompletionFunc mocks the Completion method.
	CompletionFunc func(ctx context.Context, req *llm.CompletionRequest) (*llm.CompletionResponse, error)

	// NameFunc mocks the Name method.
	NameFunc func() string

	// StreamFunc mocks the Stream method.
	StreamFunc func(ctx context.Context, req *llm.CompletionRequest) (llm.Stream, error)

	// calls tracks calls to the methods.
	calls struct {
		// Capabilities holds details about calls to the Capabilities method.
		Capabilities []struct {
		}
		// Completion holds details about calls to the Completion method.
		Completion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *llm.CompletionRequest
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// Stream holds details about calls to the Stream method.
		Stream []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *llm.CompletionRequest
		}
	}
	lockCapabilities sync.RWMutex
	lockCompletion   sync.RWMutex
	lockName         sync.RWMutex
	lockStream       sync.RWMutex
}

// Capabilities calls CapabilitiesFunc.
func (mock *ProviderMock) Capabilities() llm.Capabilities {
	if mock.CapabilitiesFunc == nil {
		panic("ProviderMock.CapabilitiesFunc: method is nil but Provider.Capabilities was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCapabilities.Lock()
	mock.calls.Capabilities = append(mock.calls.Capabilities, callInfo)
	mock.lockCapabilities.Unlock()
	return mock.CapabilitiesFunc()
}

// CapabilitiesCalls gets all the calls that were made to Capabilities.
// Check the length with:
//
//	len(mockedProvider.CapabilitiesCalls())
func (mock *ProviderMock) CapabilitiesCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCapabilities.RLock()
	calls = mock.calls.Capabilities
	mock.lockCapabilities.RUnlock()
	return calls
}

// Completion calls CompletionFunc.
func (mock *ProviderMock) Completion(ctx context.Context, req *llm.CompletionRequest) (*llm.CompletionResponse, error) {
	if mock.CompletionFunc == nil {
		panic("ProviderMock.CompletionFunc: method is nil but Provider.Completion was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *llm.CompletionRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCompletion.Lock()
	mock.calls.Completion = append(mock.calls.Completion, callInfo)
	mock.lockCompletion.Unlock()
	return mock.CompletionFunc(ctx, req)
}

// CompletionCalls gets all the calls that were made to Completion.
// Check the length with:
//
//	len(mockedProvider.CompletionCalls())
func (mock *ProviderMock) CompletionCalls() []struct {
	Ctx context.Context
	Req *llm.CompletionRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *llm.CompletionRequest
	}
	mock.lockCompletion.RLock()
	calls = mock.calls.Completion
	mock.lockCompletion.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *ProviderMock) Name() string {
	if mock.NameFunc == nil {
		panic("ProviderMock.NameFunc: method is nil but Provider.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedProvider.NameCalls())
func (mock *ProviderMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Stream calls StreamFunc.
func (mock *ProviderMock) Stream(ctx context.Context, req *llm.CompletionRequest) (llm.Stream, error) {
	if mock.StreamFunc == nil {
		panic("ProviderMock.StreamFunc: method is nil but Provider.Stream was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *llm.CompletionRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockStream.Lock()
	mock.calls.Stream = append(mock.calls.Stream, callInfo)
	mock.lockStream.Unlock()
	return mock.StreamFunc(ctx, req)
}

// StreamCalls gets all the calls that were made to Stream.
// Check the length with:
//
//	len(mockedProvider.StreamCalls())
func (mock *ProviderMock) StreamCalls() []struct {
	Ctx context.Context
	Req *llm.CompletionRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *llm.CompletionRequest
	}
	mock.lockStream.RLock()
	calls = mock.calls.Stream
	mock.lockStream.RUnlock()
	return calls
}

// Ensure, that StreamMock does implement llm.Stream.
// If this is not the case, regenerate this file with moq.
var _ llm.Stream = &StreamMock{}

// StreamMock is a mock implementation of llm.Stream.
//
//	func TestSomethingThatUsesStream(t *testing.T) {
//
//		// make and configure a mocked llm.Stream
//		mockedStream := &StreamMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			CurrentFunc: func() llm.Event {
//				panic("mock out the Current method")
//			},
//			ErrFunc: func() error {
//				panic("mock out the Err method")
//			},
//			NextFunc: func() bool {
//				panic("mock out the Next method")
//			},
//		}
//
//		// use mockedStream in code that requires llm.Stream
//		// and then make assertions.
//
//	}
type StreamMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// CurrentFunc mocks the Current method.
	CurrentFunc func() llm.Event

	// ErrFunc mocks the Err method.
	ErrFunc func() error

	// NextFunc mocks the Next method.
	NextFunc func() bool

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Current holds details about calls to the Current method.
		Current []struct {
		}
		// Err holds details about calls to the Err method.
		Err []struct {
		}
		// Next holds details about calls to the Next method.
		Next []struct {
		}
	}
	lockClose   sync.RWMutex
	lockCurrent sync.RWMutex
	lockErr     sync.RWMutex
	lockNext    sync.RWMutex
}

// Close calls CloseFunc.
func (mock *StreamMock) Close() error {
	if mock.CloseFunc == nil {
		panic("StreamMock.CloseFunc: method is nil but Stream.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedStream.CloseCalls())
func (mock *StreamMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Current calls CurrentFunc.
func (mock *StreamMock) Current() llm.Event {
	if mock.CurrentFunc == nil {
		panic("StreamMock.CurrentFunc: method is nil but Stream.Current was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCurrent.Lock()
	mock.calls.Current = append(mock.calls.Current, callInfo)
	mock.lockCurrent.Unlock()
	return mock.CurrentFunc()
}

// CurrentCalls gets all the calls that were made to Current.
// Check the length with:
//
//	len(mockedStream.CurrentCalls())
func (mock *StreamMock) CurrentCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCurrent.RLock()
	calls = mock.calls.Current
	mock.lockCurrent.RUnlock()
	return calls
}

// Err calls ErrFunc.
func (mock *StreamMock) Err() error {
	if mock.ErrFunc == nil {
		panic("StreamMock.ErrFunc: method is nil but Stream.Err was just called")
	}
	callInfo := struct {
	}{}
	mock.lockErr.Lock()
	mock.calls.Err = append(mock.calls.Err, callInfo)
	mock.lockErr.Unlock()
	return mock.ErrFunc()
}

// ErrCalls gets all the calls that were made to Err.
// Check the length with:
//
//	len(mockedStream.ErrCalls())
func (mock *StreamMock) ErrCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockErr.RLock()
	calls = mock.calls.Err
	mock.lockErr.RUnlock()
	return calls
}

// Next calls NextFunc.
func (mock *StreamMock) Next() bool {
	if mock.NextFunc == nil {
		panic("StreamMock.NextFunc: method is nil but Stream.Next was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNext.Lock()
	mock.calls.Next = append(mock.calls.Next, callInfo)
	mock.lockNext.Unlock()
	return mock.NextFunc()
}

// NextCalls gets all the calls that were made to Next.
// Check the length with:
//
//	len(mockedStream.NextCalls())
func (mock *StreamMock) NextCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNext.RLock()
	calls = mock.calls.Next
	mock.lockNext.RUnlock()
	return calls
}
