// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package clockmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v14/clock"
)

// Ensure, that ClockMock does implement clock.Clock.
// If this is not the case, regenerate this file with moq.
var _ clock.Clock = &ClockMock{}

// ClockMock is a mock implementation of clock.Clock.
//
//	func TestSomethingThatUsesClock(t *testing.T) {
//
//		// make and configure a mocked clock.Clock
//		mockedClock := &ClockMock{
//			NewTickerFunc: func(d time.Duration) clock.Ticker {
//				panic("mock out the NewTicker method")
//			},
//			NowFunc: func() time.Time {
//				panic("mock out the Now method")
//			},
//			SinceFunc: func(t time.Time) time.Duration {
//				panic("mock out the Since method")
//			},
//			SleepFunc: func(ctx context.Context, d time.Duration) error {
//				panic("mock out the Sleep method")
//			},
//		}
//
//		// use mockedClock in code that requires clock.Clock
//		// and then make assertions.
//
//	}
type ClockMock struct {
	// NewTickerFunc mocks the NewTicker method.
	NewTickerFunc func(d time.Duration) clock.Ticker

	// NowFunc mocks the Now method.
	NowFunc func() time.Time

	// SinceFunc mocks the Since method.
	SinceFunc func(t time.Time) time.Duration

	// SleepFunc mocks the Sleep method.
	SleepFunc func(ctx context.Context, d time.Duration) error

	// calls tracks calls to the methods.
	calls struct {
		// NewTicker holds details about calls to the NewTicker method.
		NewTicker []struct {
			// D is the d argument value.
			D time.Duration
		}
		// Now holds details about calls to the Now method.
		Now []struct {
		}
		// Since holds details about calls to the Since method.
		Since []struct {
			// T is the t argument value.
			T time.Time
		}
		// Sleep holds details about calls to the Sleep method.
		Sleep []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// D is the d argument value.
			D time.Duration
		}
	}
	lockNewTicker sync.RWMutex
	lockNow       sync.RWMutex
	lockSince     sync.RWMutex
	lockSleep     sync.RWMutex
}

// NewTicker calls NewTickerFunc.
func (mock *ClockMock) NewTicker(d time.Duration) clock.Ticker {
	if mock.NewTickerFunc == nil {
		panic("ClockMock.NewTickerFunc: method is nil but Clock.NewTicker was just called")
	}
	callInfo := struct {
		D time.Duration
	}{
		D: d,
	}
	mock.lockNewTicker.Lock()
	mock.calls.NewTicker = append(mock.calls.NewTicker, callInfo)
	mock.lockNewTicker.Unlock()
	return mock.NewTickerFunc(d)
}

// NewTickerCalls gets all the calls that were made to NewTicker.
// Check the length with:
//
//	len(mockedClock.NewTickerCalls())
func (mock *ClockMock) NewTickerCalls() []struct {
	D time.Duration
} {
	var calls []struct {
		D time.Duration
	}
	mock.lockNewTicker.RLock()
	calls = mock.calls.NewTicker
	mock.lockNewTicker.RUnlock()
	return calls
}

// Now calls NowFunc.
func (mock *ClockMock) Now() time.Time {
	if mock.NowFunc == nil {
		panic("ClockMock.NowFunc: method is nil but Clock.Now was just called")
	}
	callInfo := struct {
	}{}
	mock.lockNow.Lock()
	mock.calls.Now = append(mock.calls.Now, callInfo)
	mock.lockNow.Unlock()
	return mock.NowFunc()
}

// NowCalls gets all the calls that were made to Now.
// Check the length with:
//
//	len(mockedClock.NowCalls())
func (mock *ClockMock) NowCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockNow.RLock()
	calls = mock.calls.Now
	mock.lockNow.RUnlock()
	return calls
}

// Since calls SinceFunc.
func (mock *ClockMock) Since(t time.Time) time.Duration {
	if mock.SinceFunc == nil {
		panic("ClockMock.SinceFunc: method is nil but Clock.Since was just called")
	}
	callInfo := struct {
		T time.Time
	}{
		T: t,
	}
	mock.lockSince.Lock()
	mock.calls.Since = append(mock.calls.Since, callInfo)
	mock.lockSince.Unlock()
	return mock.SinceFunc(t)
}

// SinceCalls gets all the calls that were made to Since.
// Check the length with:
//
//	len(mockedClock.SinceCalls())
func (mock *ClockMock) SinceCalls() []struct {
	T time.Time
} {
	var calls []struct {
		T time.Time
	}
	mock.lockSince.RLock()
	calls = mock.calls.Since
	mock.lockSince.RUnlock()
	return calls
}

// Sleep calls SleepFunc.
func (mock *ClockMock) Sleep(ctx context.Context, d time.Duration) error {
	if mock.SleepFunc == nil {
		panic("ClockMock.SleepFunc: method is nil but Clock.Sleep was just called")
	}
	callInfo := struct {
		Ctx context.Context
		D   time.Duration
	}{
		Ctx: ctx,
		D:   d,
	}
	mock.lockSleep.Lock()
	mock.calls.Sleep = append(mock.calls.Sleep, callInfo)
	mock.lockSleep.Unlock()
	return mock.SleepFunc(ctx, d)
}

// SleepCalls gets all the calls that were made to Sleep.
// Check the length with:
//
//	len(mockedClock.SleepCalls())
func (mock *ClockMock) SleepCalls() []struct {
	Ctx context.Context
	D   time.Duration
} {
	var calls []struct {
		Ctx context.Context
		D   time.Duration
	}
	mock.lockSleep.RLock()
	calls = mock.calls.Sleep
	mock.lockSleep.RUnlock()
	return calls
}

// Ensure, that TickerMock does implement clock.Ticker.
// If this is not the case, regenerate this file with moq.
var _ clock.Ticker = &TickerMock{}

// TickerMock is a mock implementation of clock.Ticker.
//
//	func TestSomethingThatUsesTicker(t *testing.T) {
//
//		// make and configure a mocked clock.Ticker
//		mockedTicker := &TickerMock{
//			ChanFunc: func() <-chan time.Time {
//				panic("mock out the Chan method")
//			},
//			StopFunc: func()  {
//				panic("mock out the Stop method")
//			},
//		}
//
//		// use mockedTicker in code that requires clock.Ticker
//		// and then make assertions.
//
//	}
type TickerMock struct {
	// ChanFunc mocks the Chan method.
	ChanFunc func() <-chan time.Time

	// StopFunc mocks the Stop method.
	StopFunc func()

	// calls tracks calls to the methods.
	calls struct {
		// Chan holds details about calls to the Chan method.
		Chan []struct {
		}
		// Stop holds details about calls to the Stop method.
		Stop []struct {
		}
	}
	lockChan sync.RWMutex
	lockStop sync.RWMutex
}

// Chan calls ChanFunc.
func (mock *TickerMock) Chan() <-chan time.Time {
	if mock.ChanFunc == nil {
		panic("TickerMock.ChanFunc: method is nil but Ticker.Chan was just called")
	}
	callInfo := struct {
	}{}
	mock.lockChan.Lock()
	mock.calls.Chan = append(mock.calls.Chan, callInfo)
	mock.lockChan.Unlock()
	return mock.ChanFunc()
}

// ChanCalls gets all the calls that were made to Chan.
// Check the length with:
//
//	len(mockedTicker.ChanCalls())
func (mock *TickerMock) ChanCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockChan.RLock()
	calls = mock.calls.Chan
	mock.lockChan.RUnlock()
	return calls
}

// Stop calls StopFunc.
func (mock *TickerMock) Stop() {
	if mock.StopFunc == nil {
		panic("TickerMock.StopFunc: method is nil but Ticker.Stop was just called")
	}
	callInfo := struct {
	}{}
	mock.lockStop.Lock()
	mock.calls.Stop = append(mock.calls.Stop, callInfo)
	mock.lockStop.Unlock()
	mock.StopFunc()
}

// StopCalls gets all the calls that were made to Stop.
// Check the length with:
//
//	len(mockedTicker.StopCalls())
func (mock *TickerMock) StopCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockStop.RLock()
	calls = mock.calls.Stop
	mock.lockStop.RUnlock()
	return calls
}
