package envvars_test

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/primandproper/platform-go/v11/config/envvars"
)

// ExampleCollect reads the set of variables out of a module rather than writing
// it, which is what a caller wanting something other than constants — a .env
// example, a check that refuses to start on an unrecognized variable — starts
// from.
func ExampleCollect() {
	variables, err := envvars.Collect(context.Background(), envvars.Options{
		Dir:      filepath.Join("testdata", "app"),
		Prefix:   "APP_",
		UnionKey: "internal/config.configurations",
		DependencyDirs: map[string]string{
			"example.com/dep": filepath.Join("testdata", "dep"),
		},
	})
	if err != nil {
		panic(err)
	}

	for i := range variables[:3] {
		fmt.Println(variables[i].Name, "->", variables[i].FieldPaths[0])
	}

	// Output:
	// APP_ANALYTICS_POSTHOG_API_KEY -> APIServiceConfig.Analytics.Posthog.APIKey
	// APP_CHAIN_LABEL -> APIServiceConfig.Chain.Label
	// APP_DATABASE_CONNECTION_PORT -> APIServiceConfig.Database.ConnectionDetails.Port
}

// ExampleGenerate writes the constants. It is normally wired as a
// `go:generate` directive on a small main package, with OutputPath relative to
// the module root and Dependencies naming the library the configuration structs
// come from.
func ExampleGenerate() {
	dir, err := os.MkdirTemp("", "envvars")
	if err != nil {
		panic(err)
	}

	defer func() {
		_ = os.RemoveAll(dir)
	}()

	outputPath := filepath.Join(dir, "envvars", "env_vars.go")

	if err = envvars.Generate(context.Background(), envvars.Options{
		Dir:      filepath.Join("testdata", "app"),
		Prefix:   "APP_",
		UnionKey: "internal/config.configurations",
		DependencyDirs: map[string]string{
			"example.com/dep": filepath.Join("testdata", "dep"),
		},
		OutputPath: outputPath,
	}); err != nil {
		panic(err)
	}

	contents, err := os.ReadFile(outputPath)
	if err != nil {
		panic(err)
	}

	for _, line := range strings.Split(string(contents), "\n")[:5] {
		fmt.Println(line)
	}

	// Output:
	// // Code generated by github.com/primandproper/platform-go/v11/config/envvars. DO NOT EDIT.
	//
	// package envvars
	//
	// const (
}
