package envvars

import (
	"context"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"github.com/primandproper/platform-go/v12/errors"
)

// generatedHeader marks the output as generated in the form `go generate`
// consumers, linters, and review tools all recognize.
const generatedHeader = "// Code generated by github.com/primandproper/platform-go/v12/config/envvars. DO NOT EDIT."

// commentWidth is the column the per-constant documentation wraps at, counting
// the tab the const block indents by as one column.
const commentWidth = 96

// Generate writes a Go file declaring a constant for every environment variable
// that can override a field of one of the configuration structs opts names.
//
// It is meant to be run from a `go:generate` directive, and it overwrites
// opts.OutputPath wholesale — the file it writes is derived from the
// configuration structs and nothing else, so anything hand-added to it is lost
// on the next run. Where the set is wanted as data rather than as source, call
// Collect.
//
//nolint:gocritic // hugeParam: Options is taken by value so a call site can write it as a literal; this runs once, at build time
func Generate(ctx context.Context, opts Options) error {
	if err := opts.applyGenerationDefaults(); err != nil {
		return err
	}

	variables, err := Collect(ctx, opts)
	if err != nil {
		return err
	}

	source, err := render(opts.Package, variables)
	if err != nil {
		return err
	}

	path := opts.outputPath()
	if err = os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		return errors.Wrapf(err, "creating the directory for %q", path)
	}

	if err = os.WriteFile(path, source, 0o600); err != nil {
		return errors.Wrapf(err, "writing %q", path)
	}

	return nil
}

// render builds the generated file's source. It carries no package comment of
// its own: the package it lands in usually has one already, and a second would
// be a conflict the caller did not ask for.
func render(pkg string, variables []Variable) ([]byte, error) {
	var b strings.Builder

	b.WriteString(generatedHeader + "\n\n")
	b.WriteString("package " + pkg + "\n")

	if len(variables) > 0 {
		b.WriteString("\nconst (\n")

		for i := range variables {
			if i > 0 {
				b.WriteString("\n")
			}

			for _, line := range wrapComment(describe(&variables[i]), commentWidth-1) {
				b.WriteString("\t" + line + "\n")
			}

			fmt.Fprintf(&b, "\t%s = %q\n", variables[i].ConstantName, variables[i].Name)
		}

		b.WriteString(")\n")
	}

	source, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, errors.Wrap(err, "formatting the generated source")
	}

	return source, nil
}

// describe writes the documentation for one constant: what it overrides, and
// what it falls back to when it is unset.
func describe(v *Variable) string {
	paths := make([]string, 0, len(v.FieldPaths))
	for _, path := range v.FieldPaths {
		paths = append(paths, "`"+path+"`")
	}

	description := fmt.Sprintf("%s is the environment variable name to set to override %s.", v.ConstantName, strings.Join(paths, ", "))

	switch {
	case v.HasDefault && v.Default == "":
		description += " It defaults to the empty string."
	case v.HasDefault:
		description += fmt.Sprintf(" It defaults to `%s`.", v.Default)
	}

	return description
}

// wrapComment renders text as // comment lines no longer than width columns,
// breaking on spaces. A word longer than the width gets a line of its own
// rather than being broken.
func wrapComment(text string, width int) []string {
	var (
		lines   []string
		current = "//"
	)

	for word := range strings.FieldsSeq(text) {
		switch {
		case current == "//":
			current += " " + word
		case len(current)+1+len(word) <= width:
			current += " " + word
		default:
			lines = append(lines, current)
			current = "// " + word
		}
	}

	return append(lines, current)
}
