// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package distributedlockmock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform-go/v9/distributedlock"
)

// Ensure, that LockerMock does implement distributedlock.Locker.
// If this is not the case, regenerate this file with moq.
var _ distributedlock.Locker = &LockerMock{}

// LockerMock is a mock implementation of distributedlock.Locker.
//
//	func TestSomethingThatUsesLocker(t *testing.T) {
//
//		// make and configure a mocked distributedlock.Locker
//		mockedLocker := &LockerMock{
//			AcquireFunc: func(ctx context.Context, key string, ttl time.Duration) (distributedlock.Lock, error) {
//				panic("mock out the Acquire method")
//			},
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			PingFunc: func(ctx context.Context) error {
//				panic("mock out the Ping method")
//			},
//		}
//
//		// use mockedLocker in code that requires distributedlock.Locker
//		// and then make assertions.
//
//	}
type LockerMock struct {
	// AcquireFunc mocks the Acquire method.
	AcquireFunc func(ctx context.Context, key string, ttl time.Duration) (distributedlock.Lock, error)

	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// PingFunc mocks the Ping method.
	PingFunc func(ctx context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Acquire holds details about calls to the Acquire method.
		Acquire []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// Ping holds details about calls to the Ping method.
		Ping []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockAcquire sync.RWMutex
	lockClose   sync.RWMutex
	lockPing    sync.RWMutex
}

// Acquire calls AcquireFunc.
func (mock *LockerMock) Acquire(ctx context.Context, key string, ttl time.Duration) (distributedlock.Lock, error) {
	if mock.AcquireFunc == nil {
		panic("LockerMock.AcquireFunc: method is nil but Locker.Acquire was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}{
		Ctx: ctx,
		Key: key,
		TTL: ttl,
	}
	mock.lockAcquire.Lock()
	mock.calls.Acquire = append(mock.calls.Acquire, callInfo)
	mock.lockAcquire.Unlock()
	return mock.AcquireFunc(ctx, key, ttl)
}

// AcquireCalls gets all the calls that were made to Acquire.
// Check the length with:
//
//	len(mockedLocker.AcquireCalls())
func (mock *LockerMock) AcquireCalls() []struct {
	Ctx context.Context
	Key string
	TTL time.Duration
} {
	var calls []struct {
		Ctx context.Context
		Key string
		TTL time.Duration
	}
	mock.lockAcquire.RLock()
	calls = mock.calls.Acquire
	mock.lockAcquire.RUnlock()
	return calls
}

// Close calls CloseFunc.
func (mock *LockerMock) Close() error {
	if mock.CloseFunc == nil {
		panic("LockerMock.CloseFunc: method is nil but Locker.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedLocker.CloseCalls())
func (mock *LockerMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// Ping calls PingFunc.
func (mock *LockerMock) Ping(ctx context.Context) error {
	if mock.PingFunc == nil {
		panic("LockerMock.PingFunc: method is nil but Locker.Ping was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPing.Lock()
	mock.calls.Ping = append(mock.calls.Ping, callInfo)
	mock.lockPing.Unlock()
	return mock.PingFunc(ctx)
}

// PingCalls gets all the calls that were made to Ping.
// Check the length with:
//
//	len(mockedLocker.PingCalls())
func (mock *LockerMock) PingCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPing.RLock()
	calls = mock.calls.Ping
	mock.lockPing.RUnlock()
	return calls
}

// Ensure, that LockMock does implement distributedlock.Lock.
// If this is not the case, regenerate this file with moq.
var _ distributedlock.Lock = &LockMock{}

// LockMock is a mock implementation of distributedlock.Lock.
//
//	func TestSomethingThatUsesLock(t *testing.T) {
//
//		// make and configure a mocked distributedlock.Lock
//		mockedLock := &LockMock{
//			KeyFunc: func() string {
//				panic("mock out the Key method")
//			},
//			RefreshFunc: func(ctx context.Context, ttl time.Duration) error {
//				panic("mock out the Refresh method")
//			},
//			ReleaseFunc: func(ctx context.Context) error {
//				panic("mock out the Release method")
//			},
//			TTLFunc: func() time.Duration {
//				panic("mock out the TTL method")
//			},
//		}
//
//		// use mockedLock in code that requires distributedlock.Lock
//		// and then make assertions.
//
//	}
type LockMock struct {
	// KeyFunc mocks the Key method.
	KeyFunc func() string

	// RefreshFunc mocks the Refresh method.
	RefreshFunc func(ctx context.Context, ttl time.Duration) error

	// ReleaseFunc mocks the Release method.
	ReleaseFunc func(ctx context.Context) error

	// TTLFunc mocks the TTL method.
	TTLFunc func() time.Duration

	// calls tracks calls to the methods.
	calls struct {
		// Key holds details about calls to the Key method.
		Key []struct {
		}
		// Refresh holds details about calls to the Refresh method.
		Refresh []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// TTL is the ttl argument value.
			TTL time.Duration
		}
		// Release holds details about calls to the Release method.
		Release []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// TTL holds details about calls to the TTL method.
		TTL []struct {
		}
	}
	lockKey     sync.RWMutex
	lockRefresh sync.RWMutex
	lockRelease sync.RWMutex
	lockTTL     sync.RWMutex
}

// Key calls KeyFunc.
func (mock *LockMock) Key() string {
	if mock.KeyFunc == nil {
		panic("LockMock.KeyFunc: method is nil but Lock.Key was just called")
	}
	callInfo := struct {
	}{}
	mock.lockKey.Lock()
	mock.calls.Key = append(mock.calls.Key, callInfo)
	mock.lockKey.Unlock()
	return mock.KeyFunc()
}

// KeyCalls gets all the calls that were made to Key.
// Check the length with:
//
//	len(mockedLock.KeyCalls())
func (mock *LockMock) KeyCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockKey.RLock()
	calls = mock.calls.Key
	mock.lockKey.RUnlock()
	return calls
}

// Refresh calls RefreshFunc.
func (mock *LockMock) Refresh(ctx context.Context, ttl time.Duration) error {
	if mock.RefreshFunc == nil {
		panic("LockMock.RefreshFunc: method is nil but Lock.Refresh was just called")
	}
	callInfo := struct {
		Ctx context.Context
		TTL time.Duration
	}{
		Ctx: ctx,
		TTL: ttl,
	}
	mock.lockRefresh.Lock()
	mock.calls.Refresh = append(mock.calls.Refresh, callInfo)
	mock.lockRefresh.Unlock()
	return mock.RefreshFunc(ctx, ttl)
}

// RefreshCalls gets all the calls that were made to Refresh.
// Check the length with:
//
//	len(mockedLock.RefreshCalls())
func (mock *LockMock) RefreshCalls() []struct {
	Ctx context.Context
	TTL time.Duration
} {
	var calls []struct {
		Ctx context.Context
		TTL time.Duration
	}
	mock.lockRefresh.RLock()
	calls = mock.calls.Refresh
	mock.lockRefresh.RUnlock()
	return calls
}

// Release calls ReleaseFunc.
func (mock *LockMock) Release(ctx context.Context) error {
	if mock.ReleaseFunc == nil {
		panic("LockMock.ReleaseFunc: method is nil but Lock.Release was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRelease.Lock()
	mock.calls.Release = append(mock.calls.Release, callInfo)
	mock.lockRelease.Unlock()
	return mock.ReleaseFunc(ctx)
}

// ReleaseCalls gets all the calls that were made to Release.
// Check the length with:
//
//	len(mockedLock.ReleaseCalls())
func (mock *LockMock) ReleaseCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRelease.RLock()
	calls = mock.calls.Release
	mock.lockRelease.RUnlock()
	return calls
}

// TTL calls TTLFunc.
func (mock *LockMock) TTL() time.Duration {
	if mock.TTLFunc == nil {
		panic("LockMock.TTLFunc: method is nil but Lock.TTL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockTTL.Lock()
	mock.calls.TTL = append(mock.calls.TTL, callInfo)
	mock.lockTTL.Unlock()
	return mock.TTLFunc()
}

// TTLCalls gets all the calls that were made to TTL.
// Check the length with:
//
//	len(mockedLock.TTLCalls())
func (mock *LockMock) TTLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockTTL.RLock()
	calls = mock.calls.TTL
	mock.lockTTL.RUnlock()
	return calls
}

// Ensure, that ScopedLockerMock does implement distributedlock.ScopedLocker.
// If this is not the case, regenerate this file with moq.
var _ distributedlock.ScopedLocker = &ScopedLockerMock{}

// ScopedLockerMock is a mock implementation of distributedlock.ScopedLocker.
//
//	func TestSomethingThatUsesScopedLocker(t *testing.T) {
//
//		// make and configure a mocked distributedlock.ScopedLocker
//		mockedScopedLocker := &ScopedLockerMock{
//			TryWithLockFunc: func(ctx context.Context, key string, fn func(ctx context.Context) error) (bool, error) {
//				panic("mock out the TryWithLock method")
//			},
//			WithLockFunc: func(ctx context.Context, key string, fn func(ctx context.Context) error) error {
//				panic("mock out the WithLock method")
//			},
//		}
//
//		// use mockedScopedLocker in code that requires distributedlock.ScopedLocker
//		// and then make assertions.
//
//	}
type ScopedLockerMock struct {
	// TryWithLockFunc mocks the TryWithLock method.
	TryWithLockFunc func(ctx context.Context, key string, fn func(ctx context.Context) error) (bool, error)

	// WithLockFunc mocks the WithLock method.
	WithLockFunc func(ctx context.Context, key string, fn func(ctx context.Context) error) error

	// calls tracks calls to the methods.
	calls struct {
		// TryWithLock holds details about calls to the TryWithLock method.
		TryWithLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
		// WithLock holds details about calls to the WithLock method.
		WithLock []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Fn is the fn argument value.
			Fn func(ctx context.Context) error
		}
	}
	lockTryWithLock sync.RWMutex
	lockWithLock    sync.RWMutex
}

// TryWithLock calls TryWithLockFunc.
func (mock *ScopedLockerMock) TryWithLock(ctx context.Context, key string, fn func(ctx context.Context) error) (bool, error) {
	if mock.TryWithLockFunc == nil {
		panic("ScopedLockerMock.TryWithLockFunc: method is nil but ScopedLocker.TryWithLock was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Key: key,
		Fn:  fn,
	}
	mock.lockTryWithLock.Lock()
	mock.calls.TryWithLock = append(mock.calls.TryWithLock, callInfo)
	mock.lockTryWithLock.Unlock()
	return mock.TryWithLockFunc(ctx, key, fn)
}

// TryWithLockCalls gets all the calls that were made to TryWithLock.
// Check the length with:
//
//	len(mockedScopedLocker.TryWithLockCalls())
func (mock *ScopedLockerMock) TryWithLockCalls() []struct {
	Ctx context.Context
	Key string
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Key string
		Fn  func(ctx context.Context) error
	}
	mock.lockTryWithLock.RLock()
	calls = mock.calls.TryWithLock
	mock.lockTryWithLock.RUnlock()
	return calls
}

// WithLock calls WithLockFunc.
func (mock *ScopedLockerMock) WithLock(ctx context.Context, key string, fn func(ctx context.Context) error) error {
	if mock.WithLockFunc == nil {
		panic("ScopedLockerMock.WithLockFunc: method is nil but ScopedLocker.WithLock was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
		Fn  func(ctx context.Context) error
	}{
		Ctx: ctx,
		Key: key,
		Fn:  fn,
	}
	mock.lockWithLock.Lock()
	mock.calls.WithLock = append(mock.calls.WithLock, callInfo)
	mock.lockWithLock.Unlock()
	return mock.WithLockFunc(ctx, key, fn)
}

// WithLockCalls gets all the calls that were made to WithLock.
// Check the length with:
//
//	len(mockedScopedLocker.WithLockCalls())
func (mock *ScopedLockerMock) WithLockCalls() []struct {
	Ctx context.Context
	Key string
	Fn  func(ctx context.Context) error
} {
	var calls []struct {
		Ctx context.Context
		Key string
		Fn  func(ctx context.Context) error
	}
	mock.lockWithLock.RLock()
	calls = mock.calls.WithLock
	mock.lockWithLock.RUnlock()
	return calls
}
