// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"

	"github.com/primandproper/platform/authentication/totp"
)

// Ensure, that VerifierMock does implement totp.Verifier.
// If this is not the case, regenerate this file with moq.
var _ totp.Verifier = &VerifierMock{}

// VerifierMock is a mock implementation of totp.Verifier.
//
//	func TestSomethingThatUsesVerifier(t *testing.T) {
//
//		// make and configure a mocked totp.Verifier
//		mockedVerifier := &VerifierMock{
//			VerifyFunc: func(ctx context.Context, secret string, code string) error {
//				panic("mock out the Verify method")
//			},
//		}
//
//		// use mockedVerifier in code that requires totp.Verifier
//		// and then make assertions.
//
//	}
type VerifierMock struct {
	// VerifyFunc mocks the Verify method.
	VerifyFunc func(ctx context.Context, secret string, code string) error

	// calls tracks calls to the methods.
	calls struct {
		// Verify holds details about calls to the Verify method.
		Verify []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Secret is the secret argument value.
			Secret string
			// Code is the code argument value.
			Code string
		}
	}
	lockVerify sync.RWMutex
}

// Verify calls VerifyFunc.
func (mock *VerifierMock) Verify(ctx context.Context, secret string, code string) error {
	if mock.VerifyFunc == nil {
		panic("VerifierMock.VerifyFunc: method is nil but Verifier.Verify was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Secret string
		Code   string
	}{
		Ctx:    ctx,
		Secret: secret,
		Code:   code,
	}
	mock.lockVerify.Lock()
	mock.calls.Verify = append(mock.calls.Verify, callInfo)
	mock.lockVerify.Unlock()
	return mock.VerifyFunc(ctx, secret, code)
}

// VerifyCalls gets all the calls that were made to Verify.
// Check the length with:
//
//	len(mockedVerifier.VerifyCalls())
func (mock *VerifierMock) VerifyCalls() []struct {
	Ctx    context.Context
	Secret string
	Code   string
} {
	var calls []struct {
		Ctx    context.Context
		Secret string
		Code   string
	}
	mock.lockVerify.RLock()
	calls = mock.calls.Verify
	mock.lockVerify.RUnlock()
	return calls
}
