// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package authorizationmock

import (
	"context"
	"sync"

	"github.com/primandproper/platform-go/v13/authorization"
)

// Ensure, that PolicyResolverMock does implement authorization.PolicyResolver.
// If this is not the case, regenerate this file with moq.
var _ authorization.PolicyResolver = &PolicyResolverMock{}

// PolicyResolverMock is a mock implementation of authorization.PolicyResolver.
//
//	func TestSomethingThatUsesPolicyResolver(t *testing.T) {
//
//		// make and configure a mocked authorization.PolicyResolver
//		mockedPolicyResolver := &PolicyResolverMock{
//			PermissionsForRolesFunc: func(ctx context.Context, roles ...string) (*authorization.PermissionSet, error) {
//				panic("mock out the PermissionsForRoles method")
//			},
//			RolesFunc: func(ctx context.Context) ([]authorization.Role, error) {
//				panic("mock out the Roles method")
//			},
//		}
//
//		// use mockedPolicyResolver in code that requires authorization.PolicyResolver
//		// and then make assertions.
//
//	}
type PolicyResolverMock struct {
	// PermissionsForRolesFunc mocks the PermissionsForRoles method.
	PermissionsForRolesFunc func(ctx context.Context, roles ...string) (*authorization.PermissionSet, error)

	// RolesFunc mocks the Roles method.
	RolesFunc func(ctx context.Context) ([]authorization.Role, error)

	// calls tracks calls to the methods.
	calls struct {
		// PermissionsForRoles holds details about calls to the PermissionsForRoles method.
		PermissionsForRoles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Roles is the roles argument value.
			Roles []string
		}
		// Roles holds details about calls to the Roles method.
		Roles []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockPermissionsForRoles sync.RWMutex
	lockRoles               sync.RWMutex
}

// PermissionsForRoles calls PermissionsForRolesFunc.
func (mock *PolicyResolverMock) PermissionsForRoles(ctx context.Context, roles ...string) (*authorization.PermissionSet, error) {
	if mock.PermissionsForRolesFunc == nil {
		panic("PolicyResolverMock.PermissionsForRolesFunc: method is nil but PolicyResolver.PermissionsForRoles was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Roles []string
	}{
		Ctx:   ctx,
		Roles: roles,
	}
	mock.lockPermissionsForRoles.Lock()
	mock.calls.PermissionsForRoles = append(mock.calls.PermissionsForRoles, callInfo)
	mock.lockPermissionsForRoles.Unlock()
	return mock.PermissionsForRolesFunc(ctx, roles...)
}

// PermissionsForRolesCalls gets all the calls that were made to PermissionsForRoles.
// Check the length with:
//
//	len(mockedPolicyResolver.PermissionsForRolesCalls())
func (mock *PolicyResolverMock) PermissionsForRolesCalls() []struct {
	Ctx   context.Context
	Roles []string
} {
	var calls []struct {
		Ctx   context.Context
		Roles []string
	}
	mock.lockPermissionsForRoles.RLock()
	calls = mock.calls.PermissionsForRoles
	mock.lockPermissionsForRoles.RUnlock()
	return calls
}

// Roles calls RolesFunc.
func (mock *PolicyResolverMock) Roles(ctx context.Context) ([]authorization.Role, error) {
	if mock.RolesFunc == nil {
		panic("PolicyResolverMock.RolesFunc: method is nil but PolicyResolver.Roles was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockRoles.Lock()
	mock.calls.Roles = append(mock.calls.Roles, callInfo)
	mock.lockRoles.Unlock()
	return mock.RolesFunc(ctx)
}

// RolesCalls gets all the calls that were made to Roles.
// Check the length with:
//
//	len(mockedPolicyResolver.RolesCalls())
func (mock *PolicyResolverMock) RolesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockRoles.RLock()
	calls = mock.calls.Roles
	mock.lockRoles.RUnlock()
	return calls
}
