// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package smsmock

import (
	"context"
	"sync"

	"github.com/primandproper/primitives-go/v2/sms"
)

// Ensure, that SenderMock does implement sms.Sender.
// If this is not the case, regenerate this file with moq.
var _ sms.Sender = &SenderMock{}

// SenderMock is a mock implementation of sms.Sender.
//
//	func TestSomethingThatUsesSender(t *testing.T) {
//
//		// make and configure a mocked sms.Sender
//		mockedSender := &SenderMock{
//			SendSMSFunc: func(ctx context.Context, details *sms.OutboundSMS) (*sms.Receipt, error) {
//				panic("mock out the SendSMS method")
//			},
//		}
//
//		// use mockedSender in code that requires sms.Sender
//		// and then make assertions.
//
//	}
type SenderMock struct {
	// SendSMSFunc mocks the SendSMS method.
	SendSMSFunc func(ctx context.Context, details *sms.OutboundSMS) (*sms.Receipt, error)

	// calls tracks calls to the methods.
	calls struct {
		// SendSMS holds details about calls to the SendSMS method.
		SendSMS []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Details is the details argument value.
			Details *sms.OutboundSMS
		}
	}
	lockSendSMS sync.RWMutex
}

// SendSMS calls SendSMSFunc.
func (mock *SenderMock) SendSMS(ctx context.Context, details *sms.OutboundSMS) (*sms.Receipt, error) {
	if mock.SendSMSFunc == nil {
		panic("SenderMock.SendSMSFunc: method is nil but Sender.SendSMS was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Details *sms.OutboundSMS
	}{
		Ctx:     ctx,
		Details: details,
	}
	mock.lockSendSMS.Lock()
	mock.calls.SendSMS = append(mock.calls.SendSMS, callInfo)
	mock.lockSendSMS.Unlock()
	return mock.SendSMSFunc(ctx, details)
}

// SendSMSCalls gets all the calls that were made to SendSMS.
// Check the length with:
//
//	len(mockedSender.SendSMSCalls())
func (mock *SenderMock) SendSMSCalls() []struct {
	Ctx     context.Context
	Details *sms.OutboundSMS
} {
	var calls []struct {
		Ctx     context.Context
		Details *sms.OutboundSMS
	}
	mock.lockSendSMS.RLock()
	calls = mock.calls.SendSMS
	mock.lockSendSMS.RUnlock()
	return calls
}
