// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package slots

import (
	"context"
	"sync"

	"github.com/redis/go-redis/v9"
)

// Ensure, that ClusterShardsClientMock does implement ClusterShardsClient.
// If this is not the case, regenerate this file with moq.
var _ ClusterShardsClient = &ClusterShardsClientMock{}

// ClusterShardsClientMock is a mock implementation of ClusterShardsClient.
//
//	func TestSomethingThatUsesClusterShardsClient(t *testing.T) {
//
//		// make and configure a mocked ClusterShardsClient
//		mockedClusterShardsClient := &ClusterShardsClientMock{
//			ClusterShardsFunc: func(ctx context.Context) *redis.ClusterShardsCmd {
//				panic("mock out the ClusterShards method")
//			},
//		}
//
//		// use mockedClusterShardsClient in code that requires ClusterShardsClient
//		// and then make assertions.
//
//	}
type ClusterShardsClientMock struct {
	// ClusterShardsFunc mocks the ClusterShards method.
	ClusterShardsFunc func(ctx context.Context) *redis.ClusterShardsCmd

	// calls tracks calls to the methods.
	calls struct {
		// ClusterShards holds details about calls to the ClusterShards method.
		ClusterShards []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockClusterShards sync.RWMutex
}

// ClusterShards calls ClusterShardsFunc.
func (mock *ClusterShardsClientMock) ClusterShards(ctx context.Context) *redis.ClusterShardsCmd {
	if mock.ClusterShardsFunc == nil {
		panic("ClusterShardsClientMock.ClusterShardsFunc: method is nil but ClusterShardsClient.ClusterShards was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockClusterShards.Lock()
	mock.calls.ClusterShards = append(mock.calls.ClusterShards, callInfo)
	mock.lockClusterShards.Unlock()
	return mock.ClusterShardsFunc(ctx)
}

// ClusterShardsCalls gets all the calls that were made to ClusterShards.
// Check the length with:
//
//	len(mockedClusterShardsClient.ClusterShardsCalls())
func (mock *ClusterShardsClientMock) ClusterShardsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockClusterShards.RLock()
	calls = mock.calls.ClusterShards
	mock.lockClusterShards.RUnlock()
	return calls
}
