// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"context"
	"sync"
	"time"

	"github.com/primandproper/platform/authentication/tokens"
)

// Ensure, that IssuerMock does implement tokens.Issuer.
// If this is not the case, regenerate this file with moq.
var _ tokens.Issuer = &IssuerMock{}

// IssuerMock is a mock implementation of tokens.Issuer.
//
//	func TestSomethingThatUsesIssuer(t *testing.T) {
//
//		// make and configure a mocked tokens.Issuer
//		mockedIssuer := &IssuerMock{
//			IssueTokenFunc: func(ctx context.Context, subject string, expiry time.Duration, extraClaims map[string]any) (string, string, error) {
//				panic("mock out the IssueToken method")
//			},
//			ParseTokenFunc: func(ctx context.Context, token string) (tokens.Claims, error) {
//				panic("mock out the ParseToken method")
//			},
//		}
//
//		// use mockedIssuer in code that requires tokens.Issuer
//		// and then make assertions.
//
//	}
type IssuerMock struct {
	// IssueTokenFunc mocks the IssueToken method.
	IssueTokenFunc func(ctx context.Context, subject string, expiry time.Duration, extraClaims map[string]any) (string, string, error)

	// ParseTokenFunc mocks the ParseToken method.
	ParseTokenFunc func(ctx context.Context, token string) (tokens.Claims, error)

	// calls tracks calls to the methods.
	calls struct {
		// IssueToken holds details about calls to the IssueToken method.
		IssueToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Subject is the subject argument value.
			Subject string
			// Expiry is the expiry argument value.
			Expiry time.Duration
			// ExtraClaims is the extraClaims argument value.
			ExtraClaims map[string]any
		}
		// ParseToken holds details about calls to the ParseToken method.
		ParseToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockIssueToken sync.RWMutex
	lockParseToken sync.RWMutex
}

// IssueToken calls IssueTokenFunc.
func (mock *IssuerMock) IssueToken(ctx context.Context, subject string, expiry time.Duration, extraClaims map[string]any) (string, string, error) {
	if mock.IssueTokenFunc == nil {
		panic("IssuerMock.IssueTokenFunc: method is nil but Issuer.IssueToken was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Subject     string
		Expiry      time.Duration
		ExtraClaims map[string]any
	}{
		Ctx:         ctx,
		Subject:     subject,
		Expiry:      expiry,
		ExtraClaims: extraClaims,
	}
	mock.lockIssueToken.Lock()
	mock.calls.IssueToken = append(mock.calls.IssueToken, callInfo)
	mock.lockIssueToken.Unlock()
	return mock.IssueTokenFunc(ctx, subject, expiry, extraClaims)
}

// IssueTokenCalls gets all the calls that were made to IssueToken.
// Check the length with:
//
//	len(mockedIssuer.IssueTokenCalls())
func (mock *IssuerMock) IssueTokenCalls() []struct {
	Ctx         context.Context
	Subject     string
	Expiry      time.Duration
	ExtraClaims map[string]any
} {
	var calls []struct {
		Ctx         context.Context
		Subject     string
		Expiry      time.Duration
		ExtraClaims map[string]any
	}
	mock.lockIssueToken.RLock()
	calls = mock.calls.IssueToken
	mock.lockIssueToken.RUnlock()
	return calls
}

// ParseToken calls ParseTokenFunc.
func (mock *IssuerMock) ParseToken(ctx context.Context, token string) (tokens.Claims, error) {
	if mock.ParseTokenFunc == nil {
		panic("IssuerMock.ParseTokenFunc: method is nil but Issuer.ParseToken was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockParseToken.Lock()
	mock.calls.ParseToken = append(mock.calls.ParseToken, callInfo)
	mock.lockParseToken.Unlock()
	return mock.ParseTokenFunc(ctx, token)
}

// ParseTokenCalls gets all the calls that were made to ParseToken.
// Check the length with:
//
//	len(mockedIssuer.ParseTokenCalls())
func (mock *IssuerMock) ParseTokenCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockParseToken.RLock()
	calls = mock.calls.ParseToken
	mock.lockParseToken.RUnlock()
	return calls
}

// Ensure, that ClaimsMock does implement tokens.Claims.
// If this is not the case, regenerate this file with moq.
var _ tokens.Claims = &ClaimsMock{}

// ClaimsMock is a mock implementation of tokens.Claims.
//
//	func TestSomethingThatUsesClaims(t *testing.T) {
//
//		// make and configure a mocked tokens.Claims
//		mockedClaims := &ClaimsMock{
//			ExpiresAtFunc: func() time.Time {
//				panic("mock out the ExpiresAt method")
//			},
//			GetFunc: func(key string) (any, bool) {
//				panic("mock out the Get method")
//			},
//			GetStringFunc: func(key string) (string, bool) {
//				panic("mock out the GetString method")
//			},
//			JTIFunc: func() string {
//				panic("mock out the JTI method")
//			},
//			SubjectFunc: func() string {
//				panic("mock out the Subject method")
//			},
//		}
//
//		// use mockedClaims in code that requires tokens.Claims
//		// and then make assertions.
//
//	}
type ClaimsMock struct {
	// ExpiresAtFunc mocks the ExpiresAt method.
	ExpiresAtFunc func() time.Time

	// GetFunc mocks the Get method.
	GetFunc func(key string) (any, bool)

	// GetStringFunc mocks the GetString method.
	GetStringFunc func(key string) (string, bool)

	// JTIFunc mocks the JTI method.
	JTIFunc func() string

	// SubjectFunc mocks the Subject method.
	SubjectFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// ExpiresAt holds details about calls to the ExpiresAt method.
		ExpiresAt []struct {
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// GetString holds details about calls to the GetString method.
		GetString []struct {
			// Key is the key argument value.
			Key string
		}
		// JTI holds details about calls to the JTI method.
		JTI []struct {
		}
		// Subject holds details about calls to the Subject method.
		Subject []struct {
		}
	}
	lockExpiresAt sync.RWMutex
	lockGet       sync.RWMutex
	lockGetString sync.RWMutex
	lockJTI       sync.RWMutex
	lockSubject   sync.RWMutex
}

// ExpiresAt calls ExpiresAtFunc.
func (mock *ClaimsMock) ExpiresAt() time.Time {
	if mock.ExpiresAtFunc == nil {
		panic("ClaimsMock.ExpiresAtFunc: method is nil but Claims.ExpiresAt was just called")
	}
	callInfo := struct {
	}{}
	mock.lockExpiresAt.Lock()
	mock.calls.ExpiresAt = append(mock.calls.ExpiresAt, callInfo)
	mock.lockExpiresAt.Unlock()
	return mock.ExpiresAtFunc()
}

// ExpiresAtCalls gets all the calls that were made to ExpiresAt.
// Check the length with:
//
//	len(mockedClaims.ExpiresAtCalls())
func (mock *ClaimsMock) ExpiresAtCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockExpiresAt.RLock()
	calls = mock.calls.ExpiresAt
	mock.lockExpiresAt.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ClaimsMock) Get(key string) (any, bool) {
	if mock.GetFunc == nil {
		panic("ClaimsMock.GetFunc: method is nil but Claims.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedClaims.GetCalls())
func (mock *ClaimsMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetString calls GetStringFunc.
func (mock *ClaimsMock) GetString(key string) (string, bool) {
	if mock.GetStringFunc == nil {
		panic("ClaimsMock.GetStringFunc: method is nil but Claims.GetString was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGetString.Lock()
	mock.calls.GetString = append(mock.calls.GetString, callInfo)
	mock.lockGetString.Unlock()
	return mock.GetStringFunc(key)
}

// GetStringCalls gets all the calls that were made to GetString.
// Check the length with:
//
//	len(mockedClaims.GetStringCalls())
func (mock *ClaimsMock) GetStringCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGetString.RLock()
	calls = mock.calls.GetString
	mock.lockGetString.RUnlock()
	return calls
}

// JTI calls JTIFunc.
func (mock *ClaimsMock) JTI() string {
	if mock.JTIFunc == nil {
		panic("ClaimsMock.JTIFunc: method is nil but Claims.JTI was just called")
	}
	callInfo := struct {
	}{}
	mock.lockJTI.Lock()
	mock.calls.JTI = append(mock.calls.JTI, callInfo)
	mock.lockJTI.Unlock()
	return mock.JTIFunc()
}

// JTICalls gets all the calls that were made to JTI.
// Check the length with:
//
//	len(mockedClaims.JTICalls())
func (mock *ClaimsMock) JTICalls() []struct {
} {
	var calls []struct {
	}
	mock.lockJTI.RLock()
	calls = mock.calls.JTI
	mock.lockJTI.RUnlock()
	return calls
}

// Subject calls SubjectFunc.
func (mock *ClaimsMock) Subject() string {
	if mock.SubjectFunc == nil {
		panic("ClaimsMock.SubjectFunc: method is nil but Claims.Subject was just called")
	}
	callInfo := struct {
	}{}
	mock.lockSubject.Lock()
	mock.calls.Subject = append(mock.calls.Subject, callInfo)
	mock.lockSubject.Unlock()
	return mock.SubjectFunc()
}

// SubjectCalls gets all the calls that were made to Subject.
// Check the length with:
//
//	len(mockedClaims.SubjectCalls())
func (mock *ClaimsMock) SubjectCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockSubject.RLock()
	calls = mock.calls.Subject
	mock.lockSubject.RUnlock()
	return calls
}
